name: .NET Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Bomj/HomelessToMillionaire.csproj

    - name: Build project
      run: dotnet build Bomj/HomelessToMillionaire.csproj --no-restore --warnaserror
